### ISSUE TITLE
Fade effect Annoyance.

### ISSUE THREAD

**Issue by frojack** [martenjj/wallpaperswitch#12]
Wallpaper slideshow in later versions of KDE/Plasma5 have a transition effect
set to fade, with a duration of 1 second and no messing with settings seems to change this. 

This affects wallpaperswitcher.

However you can adjust the time for this in 
/usr/share/plasma/wallpapers/org.kde.slideshow/contents/config/main.xml

    <entry name="TransitionAnimationDuration" type="int">
      <label>Fade Transition Animation  (ms)</label>
      <default>0010</default>
    </entry>

Change the default from 1000 to 10 or less.
You have to be root to change this.

That still won't change it until your unlock widgets,
Log out.
Log in.

Go to Settings / System settings / Desktop Behavior / Virtual Desktop / Switching Tab

Change the transition name and either set it back to fade or set to none. (this seems to be ignored).

Then get out of desktop settings. 
Lock widgets again. It will probably be set and saved.  
Maybe you have to log out and in again at this point.  Its voodoo.  IDK. Play with it.
Eventually you can get it to speed up that transition to what ever you want. 

I suspect it gets copied somewhere into your user directory but I don't know where, or when.

This value will never be shown to you in any control applet and your changes never seem to be honored when using the standard controls so you have to hack it in this way.

**Comment by martenjj** [comment]
Thanks for the hint.  The setting there should be copied into your user settings at ~/.config/plasma-org.kde.plasma.desktop-appletsrc;  that file contains all of the settings for all Plasma applets but if you search for the pathname you enter as the slideshow location you should find a section like:

    [Containments][1][Wallpaper][org.kde.slideshow][General]
    SlideInterval=43200
    SlidePaths=/home/yourname/.local/share/wallpaperswitch

If you also add

    TransitionAnimationDuration=10

to this section, then log out and log in again, it should take effect.

Please let me know if this works, and if it does I'll add a note in the README file so that others can do the same.

**Comment by frojack** [comment]
This does seem to work.  Thanks.
I removed the change I made (it gets reverted with every kde update anyway), and added your change in.
It was preserved over logout and log in, so I am back to instant wallpaper changes, without hacking KDE system files.

**Comment by martenjj** [comment]
Now unmaintained due to Plasma changes, see README.md for further information.
