### ISSUE TITLE
How to remove it once installed?

### ISSUE THREAD

**Issue by rpgdev** [martenjj/wallpaperswitch#13]
How can I uninstall this?

**Comment by martenjj** [comment]
If you have built from source, and still have the build directory that you installed from,then there is an uninstall target.  Simply go to the same place and do `make uninstall`.

If this does not work then look to see if there is a file `install_manifest.txt` in the build directory.  If there is, then you can manually remove each file listed in it.

If this make target does not work, the file does not exist, or if you no longer have the build directory, then the files you need to manually remove are:

    /usr/share/applications/wallpaperswitch.desktop
    /usr/bin/wallpaperswitch

(where the path prefix may vary depending on your distro and where KDE is installed).

**Comment by martenjj** [comment]
Now unmaintained due to Plasma changes, see README.md for further information.
