### ISSUE TITLE
Can't build and install

### ISSUE THREAD

**Issue by leonardojpv** [martenjj/wallpaperswitch#15]
It won't install after following the instructions and installing all dependencies specified on README.kubuntu on Kubuntu 18.10 with KDE 5 (Lenovo Ideapad 320 i3 2.0Ghz / 8GBRAM)

![screenshot_20190122_130618](https://user-images.githubusercontent.com/46933042/51548347-eaf54f80-1e46-11e9-987e-6a937742eb19.png)

You would think I was supposed to be able to read the message thrown by the error, but I can't. Sorry. Please help!
I would really appreciate it. Thanks

**Comment by martenjj** [comment]
Please see updated README.kubuntu and see if 'gettext' package is needed.
