### ISSUE TITLE
Feature request - allow for selecting a folder rather than an image per desktop

### ISSUE THREAD

**Issue by phd21** [martenjj/wallpaperswitch#6]
Hello Martenjj,

First, Thank you very much for providing this wallpaper switcher app for KDE plasma 5. It works very well. Like you and many others, I am hoping that the KDE developers will bring back the custom virtual desktop workspaces with custom wallpapers and widgets (icons) that Plasma 4 already had. I truly cannot understand why they did not make every effort to include that in Plasma 5.

Here is my request: It would be really nice if we could select a particular folder for images for a desktop workspace, rather than a specific image, where your application would automatically select whatever image file is in that folder. The reason for this is that I also really like the "Variety" wallpaper changer program, and for KDE users you have to specify a particular folder like "variety-wallpaper" and the image "wallpaper-kde.jpg", only the image file name changes when the wallpaper changes to something like "wallpaper-kde**-32365**.jpg". I think that your wallpaper switcher app and the Variety wallpaper changer app would work well together if this could be done.  I already contacted the "Variety" developer to see if they could lock in the image name to just "wallpaper-kde.jpg" without adding the "-#####", but have not heard back from them yet.

Another reason is that I really enjoy having a "quotes" option on my desktop which in Plasma 5 does not exist anymore, no fortune widget or app is available that work, that I know of; but Variety's quotes works and they have some other very nice features as well.

Also, In your instructions for wallpaper switcher, you also mention that the KDE desktop slideshow option should be set to a certain time 12hrs, how necessary is that? It seems that having 10 seconds in that seconds field is necessary for Variety to work, but the hours and minutes can be changed to whatever. I was using 2 minutes 10 secs for Variety and 3 minutes 10 secs for KDE desktop slideshow options, and it seemed to work.

Thank you for your consideration.

Best regards to you and yours,
Phil
phd21

**Comment by martenjj** [comment]
Now unmaintained due to Plasma changes, see README.md for further information.
