### ISSUE TITLE
dual monitor support

### ISSUE THREAD

**Issue by zecritter** [martenjj/wallpaperswitch#8]
Hello Jonathan Marten,

Thank you a lot for this nice app. It really help me adapt to KDE 5.
Is it possible to implement support for multimonitor system. For example, for dual monitor get two slideshow for left and right monitor wallparers?

**Comment by martenjj** [comment]
Thanks for the suggestion;  it may be possible if the underlying Plasma slideshow background supports different slideshows for different monitors.  I'll investigate.

**Comment by martenjj** [comment]
Now unmaintained due to Plasma changes, see README.md for further information.
