### ISSUE TITLE
List of packages required on fresh Kubuntu Xenial install to compile this

### ISSUE THREAD

**Issue by jamadagni** [martenjj/wallpaperswitch#9]
Hello. This is the list of packages required to be installed on a fresh Kubuntu Xenial install to compile this. I arrived at this by trial and error. Might be useful to mention somewhere in the readme or wiki. I don't seem to have access to the wiki. Thanks!

build-essential
cmake
extra-cmake-modules
kio-dev
libkf5configwidgets-dev
libkf5crash-dev
libkf5iconthemes-dev
libkf5notifications-dev
libkf5widgetsaddons-dev
libkf5xmlgui-dev
plasma-workspace-dev
qtbase5-dev
qtdeclarative5-dev

**Comment by martenjj** [comment]
Many thanks for the list!  Added to README files.

**Comment by facundoq** [comment]
Note:  `kio-dev` is not available any more in 18.10. Instead, you can install `libkf5kio-dev`
